name: Build Artifact & Container
on:
  push:
    branches: [ CI-process ]
  pull_request:
    branches: [ master ]
jobs:
  amazonlinux2:
    name: Build ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Web
        uses: ./web-compile/action/amazonlinux2
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      - name: Build with Maven
        run: mvn -B package --file web-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - name: Bump Version
        if: github.event_name == 'push'
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pom-path: web-dist
      - name: Upload install file
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: web-dist/target/lena-work/
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repository
        if: github.event_name == 'push'
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=amazonlinux:2
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}
  centos7:
    name: Build ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Web
        uses: ./web-compile/action/centos7
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      - name: Build with Maven
        run: mvn -B package --file web-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - name: Bump Version
        if: github.event_name == 'push'
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pom-path: web-dist
      - name: Upload install file
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: web-dist/target/lena-work/
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repository
        if: github.event_name == 'push'
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=centos:7
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}
  centos8:
    name: Build ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Web
        uses: ./web-compile/action/centos8
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      - name: Build with Maven
        run: mvn -B package --file web-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - name: Bump Version
        if: github.event_name == 'push'
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pom-path: web-dist
      - name: Upload install file
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: web-dist/target/lena-work/
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repository
        if: github.event_name == 'push'
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=centos:8
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}
  rocky8:
    name: Build ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Web
        uses: ./web-compile/action/rocky8
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      - name: Build with Maven
        run: mvn -B package --file web-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - name: Bump Version
        if: github.event_name == 'push'
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pom-path: web-dist
      - name: Upload install file
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: web-dist/target/lena-work/
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repository
        if: github.event_name == 'push'
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=rockylinux/rockylinux:8.4
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}
  ubuntu1804:
    name: Build ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Web
        uses: ./web-compile/action/ubuntu1804
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      - name: Build with Maven
        run: mvn -B package --file web-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - name: Bump Version
        if: github.event_name == 'push'
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pom-path: web-dist
      - name: Upload install file
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: web-dist/target/lena-work/
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repository
        if: github.event_name == 'push'
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=ubuntu:18.04
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}